year_of_interest:
 begin: 1961
 end: 2022
exeptions:
 6649:
  begin: 2013
  end: 2022
 6773:
  begin: 2007
  end: 2022
 6970:
  begin: 1992
  end: 2022
 AIA:
  begin: 1980
  end: 2022  
 ARM:
  begin: 1992
  end: 2022 
 AZE:
  begin: 1992
  end: 2022   
 BLR:
  begin: 1992
  end: 2022       
 BES:
  begin: 2011
  end: 2022 
 BIH:
  begin: 1992
  end: 2022    
 HRV:
  begin: 1992
  end: 2022      
 CUW:
  begin: 2011
  end: 2022 
 CZE:
  begin: 1993
  end: 2022   
 ERI:
  begin: 1993
  end: 2022  
 EST:
  begin: 1992
  end: 2022  
 ETH:
  begin: 1993
  end: 2022   
 GEO:
  begin: 1992
  end: 2022   
 KAZ:
  begin: 1992
  end: 2022   
 KGZ:
  begin: 1992
  end: 2022 
 LVA:
  begin: 1992
  end: 2022   
 LTU:
  begin: 1992
  end: 2022  
 MHL:
  begin: 1991
  end: 2022  
 FSM:
  begin: 1991
  end: 2022       
 MNE:
  begin: 2006
  end: 2022 
 MKD:
  begin: 1992
  end: 2022 
 MNP:
  begin: 1991
  end: 2022  
 PLW:
  begin: 1981
  end: 2022    
 MDA:
  begin: 1992
  end: 2022     
 RUS:
  begin: 1992
  end: 2022       
 BLM:
  begin: 2011
  end: 2022  
 MAF:
  begin: 2011
  end: 2022 
 SRB:
  begin: 2006
  end: 2022   
 SXM:
  begin: 2011
  end: 2022   
 SVK:
  begin: 1993
  end: 2022 
 SVN:
  begin: 1992
  end: 2022    
 SSD:
  begin: 2011
  end: 2022
 TMK:
  begin: 1992
  end: 2022 
 UKR:
  begin: 1992
  end: 2022  
 UZB:
  begin: 1992
  end: 2022   
 TJK:
  begin: 1992
  end: 2022    
